# Site settings
title: Xenia Tay
email: tay.xenia@gmail.com
description: "Xenia Tay - Design and Development"
baseurl: ""
url: "http://xeniatay.com"

# Build settings
markdown: kramdown
permalink: pretty
