# Site settings
title: "Xenia Tay | Design and Development"
email: tay.xenia@gmail.com
description: "4th year Computer Science student, minoring in Fine Arts Studio at the University of Waterloo. This is Xenia's design and development portfolio."
baseurl: "http://xeniatay.com/xeniatay.github.io"
url: "http://xeniatay.com/xeniatay.github.io"

# Build settings
markdown: kramdown
permalink: pretty
